name: Build PDF
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install LaTeX
        run: sudo apt-get update && sudo apt-get install -y texlive-full
      - name: Build PDF
        run: latexmk -pdf -interaction=nonstopmode -halt-on-error asr.tex
      - name: Get Timestamp
        run : echo "TIMESTAMP=$(date '+%Y-%m-%d %T')" >> "$GITHUB_ENV"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Draft ${{ env.TIMESTAMP }}
          files: asr.pdf
          draft: true
